  services:
    sql-server:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: sql-server
      hostname: sql-server
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=MySecurePassword123!
      ports:
        - "1433:1433"
      restart: unless-stopped
      networks:
        - sql_network

  networks:
    sql_network:
      driver: bridge